language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t amitkehila/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true amitkehila/react-test npm test

after_success:
  - docker build -t amitk1986/multi-client ./client  
  - docker build -t amitk1986/multi-nginx ./nginx
  - docker build -t amitk1986/multi-server ./server
  - docker build -t amitk1986/multi-worker ./worker
# Login to the docker CLI  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take these images and push them to docker.hub
  - docker push amitk1986/multi-client
  - docker push amitk1986/multi-nginx
  - docker push amitk1986/multi-server
  - docker push amitk1986/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-490929037281'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY